version: '3.2'

services:
  httpd:
    image: custom-httpd
    build: .
    ports:
      - '8080:80'
    volumes:
      - type: bind
        source: ./html
        target: /var/www/html

  mysql:
    image: mysql
    expose:
      - '3306'
    ports:
      - '3306:3306'
    volumes:
      - mysql:/var/lib/mysql
      #- ./mysql_init:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: 'pass'
      #MYSQL_DATABASE: 'phpdb'
      #MYSQL_USER: 'user'
      #MYSQL_PASSWORD: 'pass'

volumes:
  mysql:

